### PR TITLE
Help with too big command line for large projects

### PR DESCRIPTION
**Pull request by jisikoff**
This is to deal with HUGE projects where the number of files exceeds the capabilities of command line with previous code that listed every file. This uses "directory/**.groovy" where possible and "file.groovy" where not possible depending on what codeclimate's config.json hands us on the way in. This should drastically shorten the number of files handed to the command line while still filtering for only groovy files.

### CODE REVIEW

**Comment by f-moya** [comment]
@jisikoff this is awesome, thank you for getting into this. I wasn't fully sure about the PR that I opened, exactly for the reason that you described in your comment. 

What do you think we need to merge this one ?

**Comment by jisikoff** [comment]
@fede-moya do you know a public github repo that the original code was failing on that I could test on? otherwise I will just merge this and see if it helps.  Eventually the limit will still be reached but this should make it better.

**Comment by f-moya** [comment]
Hey @jisikoff, the original report of the problem came from a private repository. I have been testing with some big public java repos on github, but seems like none of which I have tested are big enough. Could we just go whit the approach of merging and trying. I will contact the person that reported the problem and confirm if the change works. Sounds good ?

**Comment by jisikoff** [comment]
> Hey @jisikoff, the original report of the problem came from a private repository. I have been testing with some big public java repos on github, but seems like none of which I have tested are big enough. Could we just go whit the approach of merging and trying. I will contact the person that reported the problem and confirm if the change works. Sounds good ?

works for me. let me know.

**Comment by f-moya** [comment]
@jisikoff Thank you !

**Comment by jisikoff** [comment]
@fede-moya don't forget to rebuild your docker image on your end. I don't control that here.

**Pull request merged**
